### ISSUE TITLE
Checklist for milestone 2 : 

### ISSUE THREAD

**Issue by Sayanti86** [UBC-MDS/DSCI-554_MDS_Retention#12]
- [x] Create your survey using one of the survey tools suggested below
- [x] Make sure you link to a copy of the survey in the README of your Github repo for your project as well as this Milestone.

- [x] Collect data from other MDS students, 554 TAs and lab instructor (we will set time aside in this week's time slot, so make sure your survey is ready to go for then!). This data should be uploaded and stored in a private repository on github.ubc.ca (you will need to add the teaching team as collaborators to this repo). 

- [x] Please add a link to this data in the README for this Milestone.

- [x] Perform some exploratory data analysis (EDA) on your survey data, this should include:

- [x] reading the data into Python or R and creating a summary table

- [x] create at least 4 visualizations of the data, these could include

- [x] This EDA should be in one literate code document (e.g., Jupyter notebook or .Rmd) that is nicely narrated so that someone unfamiliar with the project could easily follow what you did and why. If you choose .Rmd, please also include the rendered document in your Github repo so we can easily read the output of the run code as well.

- [x] Make sure you link to a copy of this EDA in the README of your Github repo for this Milestone.

**Comment by HarjyotKaur** [comment]
Noted
