### ISSUE TITLE
To do list for Milestone 1

### ISSUE THREAD

**Issue by Sayanti86** [UBC-MDS/DSCI-554_MDS_Retention#4]
- [x] In the UBC-MDS GitHub organization on github.com, set-up a public repository with a reasonable name for your project.

- [x] Add the team member names to your project (github.com) repo's README.

- [x] Decide and agree upon a collaboration strategy (e.g., Git flow) that describes how you will work together on this project. Document your collaboration strategy in a file called CONTRIBUTING.md which should live in your Github.com repo's root directory. Examples of such files are (remember to provide attribution if you use any of these as a basis for your own!):
Software Carpentry CONTRIBUTING.md
factory_bot_rails CONTRIBUTING.md
moby CONTRIBUTING.md

- [x] Decide and agree upon a code of conduct for contributing to your project. Document this in a file called CONDUCT.md, which should live in your Github.com repo's root directory. Examples of such files are (remember to provide attribution if you use any of these as a basis for your own!):
screed code of conduct
tidytext code of conduct

- [x] Read UBC Office of Research Ethics document on Using Online Surveys.

- [x] Identify the question that your team in interested in answering with the survey. The aim of the survey should be to try to answer one specific and testable question. Examples of specific and testable questions include (you can use one of these if you really like them):

- [x] Identify the other questions you plan to ask in your survey to identify confounding variables and justify/explain why you plan to include them.

- [x] Describe how you plan to analyze the survey results (e.g., what statistical test(s) do you plan to employ?). @Mikeymice 

- [x] Discuss the aspects of the UBC Office of Research Ethics document on Using Online Surveys that are relevant to your proposed survey.@Sayanti86
